{
 "title": "Rust DKG Engine - Tasks V2",
 "tags": [
  "rust-dkg-engine",
  "tasks",
  "v2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Execution Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Execution Duration p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_task_duration_seconds{quantile=\"0.5\",status=\"completed\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Task Execution Duration p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_task_duration_seconds{quantile=\"0.95\",status=\"completed\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Task Execution Duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_task_duration_seconds{quantile=\"0.99\",status=\"completed\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "Execution Cadence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Task Execution Cadence p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_task_cadence_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Task Execution Cadence p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_task_cadence_seconds{quantile=\"0.95\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Task Execution Cadence p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_task_cadence_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}